// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq6Mzf7YZ_ZDDOoXvxiWqP-hCU1xvSq2k',
    appId: '1:581514610835:web:a7d2df4b47a1cc5d0c6566',
    messagingSenderId: '581514610835',
    projectId: 'my-app-quiz-e1dac',
    authDomain: 'my-app-quiz-e1dac.firebaseapp.com',
    storageBucket: 'my-app-quiz-e1dac.appspot.com',
    measurementId: 'G-1KGC2XDMWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOR1IB-KbJ_DPsMyXKIyqZp_5hm4UbgPk',
    appId: '1:581514610835:android:42f8cd1b19042d270c6566',
    messagingSenderId: '581514610835',
    projectId: 'my-app-quiz-e1dac',
    storageBucket: 'my-app-quiz-e1dac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC31_j7xH1cIn4xHoR3r4JtqfqRfC9_l14',
    appId: '1:581514610835:ios:0f2303a7260c0f8b0c6566',
    messagingSenderId: '581514610835',
    projectId: 'my-app-quiz-e1dac',
    storageBucket: 'my-app-quiz-e1dac.appspot.com',
    iosClientId: '581514610835-t5erjtcfbl16ufeagkfgkld3kag2peak.apps.googleusercontent.com',
    iosBundleId: 'com.secit.ahmedsherif.qzapp.qiuzapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC31_j7xH1cIn4xHoR3r4JtqfqRfC9_l14',
    appId: '1:581514610835:ios:0fb3507ab9ea04aa0c6566',
    messagingSenderId: '581514610835',
    projectId: 'my-app-quiz-e1dac',
    storageBucket: 'my-app-quiz-e1dac.appspot.com',
    iosClientId: '581514610835-b2omr7b79g1ipq0v5b83sens57o2e8a6.apps.googleusercontent.com',
    iosBundleId: 'com.secit.ahmedsherif.qzapp.quiz',
  );
}
